name: Prod - Build and Deploy on release

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:

  build-hashnode-starter-kit:
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/build-push-ecr
        with:
          module-name: ${{ env.CI_REPOSITORY_NAME_SLUG }}
          build-for-environment: prod
          # extra-build-args: "-f docker/mindsdb.Dockerfile"

  deploy:
    runs-on: [self-hosted, prod]
    needs: [build-hashnode-starter-kit]
    environment:
      name: prod
      url: https://mindsdb.com/blog
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
      - uses: DevOps-Nirvana/aws-helm-multi-deploy-nodocker@v2
        with:
          environment-slug: prod
          k8s-namespace: prod
          image-tag: prod-${{ env.SLUG }}
          timeout: 600s
